title: My first github age website
author: Abhishek Dua
email: iwonttellmyemail@noemail.com
description: I have nothing to say

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
